integrationTest:
  # test cases and their correct pattern names
  cases:
    #3D
    '111': ['999', 'AAA']
    '000': ['999', 'AAA']
    '012': ['999', 'ABC']
    '789': ['999', 'ABC']
    '134': ['999']
    '122': ['999', 'ABB']
    '121': ['999', 'ABA']
    '112': ['999', 'AAB']
    '000Â°': ['360Degree']
    '001Â°': ['360Degree']
    '144Â°': ['360Degree']
    '360Â°': ['360Degree']
    '361Â°': []
    '0Â°': []
    '01Â°': []

    #4D
    '1345': ['10k']
    '2345': ['10k', 'ABCD']
    '3456': ['10k', 'ABCD']
    '0123': ['10k', 'ABCD', 'MMDD', '0XXX']
    '1111': ['10k', 'AAAA', 'MMDD']
    '1333': ['10k', 'ABBB']
    '3322': ['10k', 'AABB']
    '3332': ['10k', 'AAAB']
    '9099': ['10k', 'ABAA']
    '9919': ['10k', 'AABA']
    '1331': ['10k', 'ABBA']
    '1313': ['10k', 'ABAB']
    '2243': ['10k', 'AABC']
    '1233': ['10k', 'ABCC']
    '1334': ['10k', 'ABBC']
    '0134': ['10k', '0XXX']
    '0034': ['10k', '0XXX', '00XX', 'AABC']
    '0102': ['10k', '0XXX', '0X0X', 'MMDD']
    '0140': ['10k', '0XXX', '0XX0']
    '7900': ['10k', 'XX00', 'ABCC']
    '1488': ['10k', 'XX88', 'ABCC']
    '3169': ['10k', 'XX69']

    #TimesTable
    '1101': ['10k', 'AABA', 'MMDD', 'TimesTable']
    '3824': ['10k', 'TimesTable']
    '0101': ['10k', 'ABAB', '0XXX', '0X0X', 'MMDD']
    '9981': ['10k', 'AABC', 'TimesTable']

    #MMDD
    '1231': ['10k', 'MMDD']
    '0228': ['10k', 'ABBC', '0XXX', 'MMDD']
    '1029': ['10k', 'MMDD']
    '1131': ['10k', 'AABA']
    '0230': ['10k', '0XX0', '0XXX']

    #5D
    '11111': ['100k', 'AAAAA']
    '12222': ['100k', 'ABBBB']
    '11222': ['100k', 'AABBB']
    '11122': ['100k', 'AAABB']
    '11112': ['100k', 'AAAAB']
    '12221': ['100k', 'ABBBA']
    '12121': ['100k', 'ABABA']
    '00130': ['100k', '00XX0', '00XXX']
    '13420': ['100k', 'XX420']
    '11233': ['100k', 'AABCC']

    '01234': ['100k', 'ABCDE', 'XABCD']
    '56789': ['100k', 'ABCDE', 'XABCD']
    '14678': ['100k']
    '15678': ['100k', 'XABCD']

    #6D
    '111111': ['AAAAAA']
    '122222': ['ABBBBB']
    '123420': ['XXX420']

    #AshareCode
    '000000': ['AShareCode', 'AAAAAA', '00XX00', 'XXX000', '000XXX']
    '000999': ['AShareCode', 'AAABBB', '000XXX']
    '001000': ['00XX00', 'XXX000']
    '600000': ['AShareCode', 'WanClub', 'ABBBBB', 'XXX000']
    '600231': ['AShareCode']
    '601999': ['AShareCode']
    '602000': ['XXX000']
    '602999': []
    '603000': ['AShareCode', 'XXX000']
    '603999': ['AShareCode']
    '604000': ['XXX000']

    #>6D
    '1112222': ['AAABBBB']
    '11112222': ['AAAABBBB']
    '1223221': ['ABBCBBA']
    #WanClub
    '10000': ['100k', 'ABBBB', 'XX000', 'XXX00', 'WanClub']
    '20000': ['100k', 'ABBBB', 'XX000', 'XXX00', 'WanClub']
    '100000': ['ABBBBB', 'XXX000', 'WanClub']
    '0000000': []
    '1000000': ['WanClub']
    '9990000': ['AAABBBB', 'WanClub']
    '13911111111': ['XXXAAAAAAAA']
    '13911111110': []
    '14911111111': []
    '15999999999': ['XXXAAAAAAAA']

    #Alternative digits & Flags
    'é›¶é™¸æ¼†': ['999JP']
    'ç–ç–ç–': ['999JP']
    'é›¶é›¶é›¶': ['999JP', '999CN']
    'é›¶ä¸€ä¸€': ['999CN']
    'ä¹ä¹ä¹': ['999CN']
    'Ù Ù Ù ': ['Arabic999']
    'Ù Ù¢Ù©': ['Arabic999']
    'Ù©Ù©Ù©': ['Arabic999']
    'Ù Ù Ù Ù ': ['Arabic10k']
    'Ù Ù¢Ù©Ù ': ['Arabic10k']
    'Ù©Ù©Ù©Ù©': ['Arabic10k']
    'ğŸ‡ºğŸ‡¸000': ['Flag999']
    'ğŸ‡ºğŸ‡¸464': ['Flag999']
    'ğŸ‡¨ğŸ‡³999': ['Flag999']
    'ğŸ‡ºğŸ‡¦124': ['Flag999']
    'ğŸ‡¹ğŸ‡­999': ['Flag999']
    'ğŸ‡¹ğŸ‡·999': []
    'ğŸ‡ºğŸ‡¸ğŸ‡ºğŸ‡¸0': []
    'ğŸ‡ºğŸ‡¸0001': []
    'ğŸ‡ºğŸ‡¸0': []
    'ğŸ‡ºğŸ‡¸ğŸ‡¨ğŸ‡³1': []
    '001ğŸ‡ºğŸ‡¸': []

    #hex
    '0x0': ['0x9', '1Hex']
    '0x9': ['0x9', '1Hex']
    '0xa': ['1Hex']
    '0xf': ['1Hex']
    '0xg': []
    '0x00': ['0x99', '2Hex']
    '0x99': ['0x99', '2Hex']
    '0x0a': ['2Hex']
    '0xff': ['2Hex']
    '0xfg': []
    '0x000': ['0x999', '3Hex']
    '0x999': ['0x999', '3Hex']
    '0x00a': ['3Hex']
    '0xfff': ['3Hex']
    '0xffg': []
    '0x0000': ['0x10k']
    '0x1234': ['0x10k']
    '0x9999': ['0x10k']
